---
- name: creating ec2 instance
  hosts: server
  gather_facts: no
  remote_user: root
  become: true
  tasks:
          - name: create ec2 instance
            ec2:
                    key_name: India-KP
                    instance_type: t2.micro
                    image: ami-010aff33ed5991201
                    wait: true
                    group: Web-Access
                    count: 1
                    region: ap-south-1
                    state: present
                    aws_access_key: "AKIAUMFTTWR36VPJIESG"
                    aws_secret_key: "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"
                    instance_tags:
                            Name: Myec2ins1
            register: ec2 
                           
